# Generated by Django 3.1.7 on 2021-03-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='floorArea',
            field=models.FloatField(),
        ),
    ]
