# Generated by Django 3.1.7 on 2021-03-08 18:42
import sys
import os
import django
import csv

from django.db import migrations

from househunt.models import HDBResaleFlat


def run(apps, schema_editor):
    HDBResaleFlat.objects.all().delete()

    with open(os.path.join(os.getcwd(), "CZ2006", "utility","resale-flat-prices.csv"),  encoding="utf-8") as f:
        reader = csv.reader(f)
        next(reader)  # Advance past the header


        for row in csv.reader(['one,two,three']):
            #print(row)
            HDBResaleFlat.objects.create(month = row[0], town = row[1])

class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run),
    ]
