# Generated by Django 3.1.7 on 2021-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0002_auto_20210310_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='resalePrice',
            field=models.FloatField(),
        ),
    ]
