# Generated by Django 3.1.7 on 2021-03-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0003_auto_20210310_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='flatType',
            field=models.CharField(choices=[('1 ROOM', '1 ROOM'), ('2 ROOM', '2 ROOM'), ('3 ROOM', '3 ROOM'), ('4 ROOM', '4 ROOM'), ('5 ROOM', '5 ROOM'), ('EXECUTIVE', 'EXECUTIVE'), ('MULTI-GENERATION', 'MULTI-GENERATION')], max_length=50),
        ),
    ]
