# Generated by Django 3.1.7 on 2021-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0004_auto_20210310_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='town',
            field=models.CharField(choices=[('ANG MO KIO', 'ANG MO KIO'), ('BEDOK', 'BEDOK'), ('BISHAN', 'BISHAN'), ('BUKIT BATOK', 'BUKIT BATOK'), ('BUKIT MERAH', 'BUKIT MERAH'), ('BUKIT PANJANG', 'BUKIT PANJANG'), ('BUKIT TIMAH', 'BUKIT TIMAH'), ('CENTRAL AREA', 'CENTRAL AREA'), ('CHOA CHU KANG', 'CHOA CHU KANG'), ('CLEMENTI', 'CLEMENTI'), ('GEYLANG', 'GEYLANG'), ('HOUGANG', 'HOUGANG'), ('JURONG EAST', 'JURONG EAST'), ('JURONG WEST', 'JURONG WEST'), ('KALLANG/WHAMPOA', 'KALLANG/WHAMPOA'), ('MARINE PARADE', 'MARINE PARADE'), ('PASIR RIS', 'PASIR RIS'), ('PUNGGOL', 'PUNGGOL'), ('QUEENSTOWN', 'QUEENSTOWN'), ('SEMBAWANG', 'SEMBAWANG'), ('SENGKANG', 'SENGKANG'), ('SERANGOON', 'SERANGOON'), ('TAMPINES', 'TAMPINES'), ('TOA PAYOH', 'TOA PAYOH'), ('WOODLANDS', 'WOODLANDS'), ('YISHUN', 'YISHUN')], max_length=150),
        ),
    ]
