# Generated by Django 3.1.7 on 2021-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0005_auto_20210310_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='flatModel',
            field=models.CharField(choices=[('2-room', '2-room'), ('Adjoined flat', 'Adjoined flat'), ('Apartment', 'Apartment'), ('DBSS', 'DBSS'), ('Improved', 'Improved'), ('Improved-Maisonette', 'Improved-Maisonette'), ('Maisonette', 'Maisonette'), ('Model A', 'Model A'), ('Model A-Maisonette', 'Model A-Maisonette'), ('Model A2', 'Model A2'), ('Multi Generation', 'Multi Generation'), ('New Generation', 'New Generation'), ('Premium Apartment', 'Premium Apartment'), ('Premium Apartment Loft', 'Premium Apartment Loft'), ('Premium Maisonette', 'Premium Maisonette'), ('Simplified', 'Simplified'), ('Standard', 'Standard'), ('Terrace', 'Terrace'), ('Type S1', 'Type S1'), ('Type S2', 'Type S2')], max_length=50),
        ),
    ]
