# Generated by Django 3.1.7 on 2021-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('househunt', '0006_auto_20210311_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='flatModel',
            field=models.CharField(blank=True, choices=[('2-room', '2-room'), ('Adjoined flat', 'Adjoined flat'), ('Apartment', 'Apartment'), ('DBSS', 'DBSS'), ('Improved', 'Improved'), ('Improved-Maisonette', 'Improved-Maisonette'), ('Maisonette', 'Maisonette'), ('Model A', 'Model A'), ('Model A-Maisonette', 'Model A-Maisonette'), ('Model A2', 'Model A2'), ('Multi Generation', 'Multi Generation'), ('New Generation', 'New Generation'), ('Premium Apartment', 'Premium Apartment'), ('Premium Apartment Loft', 'Premium Apartment Loft'), ('Premium Maisonette', 'Premium Maisonette'), ('Simplified', 'Simplified'), ('Standard', 'Standard'), ('Terrace', 'Terrace'), ('Type S1', 'Type S1'), ('Type S2', 'Type S2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='flatType',
            field=models.CharField(blank=True, choices=[('1 ROOM', '1 ROOM'), ('2 ROOM', '2 ROOM'), ('3 ROOM', '3 ROOM'), ('4 ROOM', '4 ROOM'), ('5 ROOM', '5 ROOM'), ('EXECUTIVE', 'EXECUTIVE'), ('MULTI-GENERATION', 'MULTI-GENERATION')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='floorArea',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='remainingLease',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='resalePrice',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='storeyRange',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='hdbresaleflat',
            name='town',
            field=models.CharField(blank=True, choices=[('ANG MO KIO', 'ANG MO KIO'), ('BEDOK', 'BEDOK'), ('BISHAN', 'BISHAN'), ('BUKIT BATOK', 'BUKIT BATOK'), ('BUKIT MERAH', 'BUKIT MERAH'), ('BUKIT PANJANG', 'BUKIT PANJANG'), ('BUKIT TIMAH', 'BUKIT TIMAH'), ('CENTRAL AREA', 'CENTRAL AREA'), ('CHOA CHU KANG', 'CHOA CHU KANG'), ('CLEMENTI', 'CLEMENTI'), ('GEYLANG', 'GEYLANG'), ('HOUGANG', 'HOUGANG'), ('JURONG EAST', 'JURONG EAST'), ('JURONG WEST', 'JURONG WEST'), ('KALLANG/WHAMPOA', 'KALLANG/WHAMPOA'), ('MARINE PARADE', 'MARINE PARADE'), ('PASIR RIS', 'PASIR RIS'), ('PUNGGOL', 'PUNGGOL'), ('QUEENSTOWN', 'QUEENSTOWN'), ('SEMBAWANG', 'SEMBAWANG'), ('SENGKANG', 'SENGKANG'), ('SERANGOON', 'SERANGOON'), ('TAMPINES', 'TAMPINES'), ('TOA PAYOH', 'TOA PAYOH'), ('WOODLANDS', 'WOODLANDS'), ('YISHUN', 'YISHUN')], max_length=150),
        ),
    ]
